name: JavaScript Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.js'
      - '**.ts'
      - '**.vue'
      - '**.json'
      - '.github/workflows/js-tests.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.js'
      - '**.ts'
      - '**.vue'

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        run: yarn eslint verenigingen --ext .js,.vue --max-warnings 0

  unit-tests:
    name: Jest Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Jest tests
        run: yarn test --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          directory: coverage
          flags: jest
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Build Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build production assets
        run: yarn build --app verenigingen

      - name: Check bundle size
        run: |
          find verenigingen/public/dist -name "*.js" -exec ls -lh {} \;
          find verenigingen/public/dist -name "*.css" -exec ls -lh {} \;
