name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        # Install project dependencies if requirements.txt exists
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Install Frappe dependencies for import resolution
        pip install frappe-bench || true
    - name: Analysing the code with pylint
      run: |
        # Use the .pylintrc configuration if it exists
        if [ -f .pylintrc ]; then
          pylint verenigingen --rcfile=.pylintrc --fail-under=6.0 --exit-zero
        else
          pylint $(git ls-files '*.py') --fail-under=6.0 --exit-zero
        fi
