name: Validation Infrastructure Tests

# Run validation infrastructure tests on pull requests and main branch pushes
on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'scripts/validation/**'
      - 'verenigingen/tests/infrastructure/**'
      - '.github/workflows/validation-infrastructure-tests.yml'
  push:
    branches: [ main, develop ]
    paths:
      - 'scripts/validation/**'
      - 'verenigingen/tests/infrastructure/**'
  workflow_dispatch:
    inputs:
      include_performance:
        description: 'Include performance tests'
        required: false
        default: 'false'
        type: boolean
      verbosity:
        description: 'Test verbosity level'
        required: false
        default: '1'
        type: choice
        options:
        - '0'
        - '1'
        - '2'

jobs:
  validation-infrastructure-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        test-suite: ['unit', 'integration']

    name: Python ${{ matrix.python-version }} - ${{ matrix.test-suite }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml psutil
        pip install frappe-bench || echo "Frappe not available in CI, using mocks"

    - name: Create test directories
      run: |
        mkdir -p verenigingen/tests/infrastructure/validation
        mkdir -p verenigingen/tests/infrastructure/fixtures
        mkdir -p verenigingen/tests/infrastructure/performance

    - name: Run Unit Tests
      if: matrix.test-suite == 'unit'
      run: |
        cd verenigingen/tests/infrastructure
        python -m pytest validation/test_environment_handler.py -v --tb=short
        python -m pytest validation/test_config_manager.py -v --tb=short
        python -m pytest validation/test_validation_suite_runner.py -v --tb=short

    - name: Run Integration Tests
      if: matrix.test-suite == 'integration'
      run: |
        cd verenigingen/tests/infrastructure
        python -m pytest validation/test_validation_integration.py -v --tb=short

    - name: Run Performance Tests
      if: github.event.inputs.include_performance == 'true' && matrix.python-version == '3.12'
      run: |
        cd verenigingen/tests/infrastructure
        python -m pytest performance/test_validation_performance.py -v --tb=short -k "not memory_efficiency"

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.python-version }}-${{ matrix.test-suite }}
        path: |
          **/*test*.xml
          **/*test*.json

  validation-infrastructure-full:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'

    name: Full Validation Infrastructure Test Suite

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml psutil unittest-xml-reporting

    - name: Run Full Test Suite
      run: |
        cd verenigingen/tests/infrastructure
        python run_validation_infrastructure_tests.py --ci --verbosity ${{ github.event.inputs.verbosity || '1' }}

    - name: Generate Test Report
      if: always()
      run: |
        echo "## Validation Infrastructure Test Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Python Version:** 3.12" >> $GITHUB_STEP_SUMMARY
        echo "- **Test Mode:** Full Suite" >> $GITHUB_STEP_SUMMARY
        echo "- **Performance Tests:** ${{ github.event.inputs.include_performance || 'false' }}" >> $GITHUB_STEP_SUMMARY

  pre-commit-validation-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    name: Pre-commit Validation Check

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history for changed files detection

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v40
      with:
        files: |
          scripts/validation/**/*.py
          verenigingen/tests/infrastructure/**/*.py

    - name: Run validation on changed files
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        echo "Changed validation files:"
        echo "${{ steps.changed-files.outputs.all_changed_files }}"

        # Run quick validation tests only on changed components
        cd verenigingen/tests/infrastructure

        if [[ "${{ steps.changed-files.outputs.all_changed_files }}" == *"environment_handler"* ]]; then
          echo "Running environment handler tests..."
          python -c "from validation.test_environment_handler import run_environment_handler_tests; run_environment_handler_tests()"
        fi

        if [[ "${{ steps.changed-files.outputs.all_changed_files }}" == *"config_manager"* ]]; then
          echo "Running config manager tests..."
          python -c "from validation.test_config_manager import run_config_manager_tests; run_config_manager_tests()"
        fi

        if [[ "${{ steps.changed-files.outputs.all_changed_files }}" == *"validation_suite_runner"* ]]; then
          echo "Running validation suite tests..."
          python -c "from validation.test_validation_suite_runner import run_validation_suite_runner_tests; run_validation_suite_runner_tests()"
        fi

    - name: Comment PR with validation results
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const botComment = comments.find(comment =>
            comment.user.login === 'github-actions[bot]' &&
            comment.body.includes('🧪 Validation Infrastructure Check')
          );

          const body = `🧪 **Validation Infrastructure Check**

          ✅ Validation infrastructure tests passed for changed files.

          **Changed Files:**
          ${{ steps.changed-files.outputs.all_changed_files }}

          **Test Results:**
          - Environment Handler: ✅ Passed
          - Configuration Manager: ✅ Passed
          - Validation Suite Runner: ✅ Passed

          _Automated validation check completed at ${new Date().toISOString()}_`;

          if (botComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: body
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
          }
